// Interface automatically generated by schemas-to-ts

import { Seo } from '../../../../components/shared/interfaces/Seo';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';

export interface Page {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    shortName?: string;
    contentSections?: any;
    slug?: string;
    heading?: string;
    description?: string;
    seo?: Seo;
    locale: string;
    localizations?: { data: Page[] };
  };
}
export interface Page_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  shortName?: string;
  contentSections?: any;
  slug?: string;
  heading?: string;
  description?: string;
  seo?: Seo_Plain;
  locale: string;
  localizations?: Page[];
}

export interface Page_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  shortName?: string;
  contentSections?: any;
  slug?: string;
  heading?: string;
  description?: string;
  seo?: Seo_NoRelations;
  locale: string;
  localizations?: Page[];
}

export interface Page_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  shortName?: string;
  contentSections?: any;
  slug?: string;
  heading?: string;
  description?: string;
  seo?: Seo_Plain;
  locale: string;
  localizations?: Page[];
}
