// Interface automatically generated by schemas-to-ts

import { Media } from '../../shared/interfaces/Media';

export interface Metadata {
  metaTitle: string;
  metaDescription: string;
  metaSiteName?: string;
  metaImage: { data: Media };
}
export interface Metadata_Plain {
  metaTitle: string;
  metaDescription: string;
  metaSiteName?: string;
  metaImage: Media;
}

export interface Metadata_NoRelations {
  metaTitle: string;
  metaDescription: string;
  metaSiteName?: string;
  metaImage: number;
}

