// Interface automatically generated by schemas-to-ts

import { Media } from './Media';

export interface Seo {
  metaTitle: string;
  metaDescription: string;
  metaImage: { data: Media };
  keywords?: string;
  structuredData?: any;
}
export interface Seo_Plain {
  metaTitle: string;
  metaDescription: string;
  metaImage: Media;
  keywords?: string;
  structuredData?: any;
}

export interface Seo_NoRelations {
  metaTitle: string;
  metaDescription: string;
  metaImage: number;
  keywords?: string;
  structuredData?: any;
}

