// Interface automatically generated by schemas-to-ts

export type MediaFormat = {
  name: string
  hash: string
  ext: string
  mime: string
  width: number
  height: number
  size: number
  path: string
  url: string
}
